name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - awkward
  - uproot
  - vector
  - pip
  - pip:
      - mt2
      - atlasopenmagic
